---
- name: DNF | Configure Docker repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: "https://yum.dockerproject.org/repo/main/{{ ansible_distribution|lower}}/{{ ansible_distribution_major_version }}/"
    enabled: 1
    gpgcheck: 1
    gpgkey: https://yum.dockerproject.org/gpg

- name: DNF | Install Docker Application
  dnf: name=docker-engine state=present
