# Create 2 Pools, HTTPPolicySet to direct traffic to each, and Virtual Service
---
- hosts: localhost
  connection: local
  vars:
    controller: 10.10.27.90
    username: admin
    password: AviNetworks123!
    tenant: admin
  tasks:
  - avi_httppolicyset:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      name: test-HTTP-Policy-Set
      tenant_ref: admin
      state: absent
      http_request_policy:
        rules:
          - index: 1
            enable: true
            name: test-test1
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /test1
                match_criteria: EQUALS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: '/api/pool?name=testpool1'
          - index: 2
            enable: true
            name: test-test2
            match:
              path:
                match_case: INSENSITIVE
                match_str:
                  - /test2
                match_criteria: CONTAINS
            switching_action:
              action: HTTP_SWITCHING_SELECT_POOL
              status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_200
              pool_ref: '/api/pool?name=testpool2'
      is_internal_policy: false
