# Remove a Virtual Service, and it's corresponding Pool.
---
- hosts: localhost
  connection: local
  vars:
    controller: 10.10.27.90
    username: admin
    password: AviNetworks123!
    tenant: admin
  tasks:
  - avi_virtualservice:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      name: newtestvs
      state: absent
      performance_limits:
        max_concurrent_connections: 1000
      services:
        - port: 443
          enable_ssl: true
        - port: 80
      ssl_profile_ref: '/api/sslprofile?name=System-Standard'
      application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
      ssl_key_and_certificate_refs:
        - '/api/sslkeyandcertificate?name=System-Default-Cert'
      ip_address:
        addr: 10.90.131.105
        type: V4
      pool_ref: '/api/pool?name=testpool2'
  - avi_pool:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      name: testpool1
      state: absent
      health_monitor_refs:
        - '/api/healthmonitor?name=System-HTTP'
      servers:
        - ip:
            addr: 10.90.130.8
            type: V4
        - ip:
            addr: 10.90.130.7
            type: V4
