# Create pool, 1 VIP, and assign SSL Certificate to Pool
---
- hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avisdk
  tasks:
    - avi_pool:
        controller: 10.90.115.20
        username: admin
        password: Avi12345
        tenant: admin
        name: testpool1
        state: present
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: 10.90.130.8
              type: V4
          - ip:
              addr: 10.90.130.7
              type: V4
    - avi_virtualservice:
        controller: 10.90.115.20
        username: admin
        password: Avi12345
        tenant: admin
        name: newtestvs
        state: present
        performance_limits:
          max_concurrent_connections: 1000
        services:
          - port: 443
            enable_ssl: true
          - port: 80
        ssl_profile_ref: '/api/sslprofile?name=System-Standard'
        application_profile_ref: '/api/applicationprofile?name=System-Secure-HTTP'
        ssl_key_and_certificate_refs:
          - '/api/sslkeyandcertificate?name=System-Default-Cert'
        ip_address:
          addr: 10.90.131.105
          type: V4
        pool_ref: '/api/pool?name=testpool1'
