---
# ansible-playbook user_create.yml -e "master_ctl_ip=10.10.20.10,master_ctl_username=admin,..."
- hosts: localhost
  vars:
    master_ctl_ip: ec2-34-250-111-254.eu-west-1.compute.amazonaws.com
    master_ctl_username: admin
    master_ctl_password: AviNetworks123!
    avi_users:
      - username: eanderson
        name: Eric Anderson
        password: AviNetworks123!
      - username: eanderson1
        name: Eric Anderson1
        password: AviNetworks123!
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Check if user exists on Avi
      avi_api_session:
        controller: "{{ master_ctl_ip }}"
        username: "{{ master_ctl_username }}"
        password: "{{ master_ctl_password }}"
        http_method: get
        path: user?name={{ item.username }}
      register: user_exists
      with_items:
        - "{{ avi_users }}"

    - debug: var=user_exists

    - name: Create User on Avi
      avi_api_session:
        controller: "{{ master_ctl_ip }}"
        username: "{{ master_ctl_username }}"
        password: "{{ master_ctl_password }}"
        http_method: post
        path: user
        data:
          require_password_confirmation: false
          is_active: true
          access:
            - tenant_ref: '/api/tenant?name=admin'
              role_ref: '/api/role?name=System-Admin'
          default_tenant_ref: '/api/tenant?name=admin'
          full_name: "{{ item.item.name }}"
          username: "{{ item.item.username }}"
          password: "{{ item.item.password }}"
      when: item.obj.count < 1
      with_items:
        - "{{ user_exists.results }}"
