---
- hosts: all
  vars:
    avi_version: latest
  roles:
    - role: avinetworks.docker
    - role: avinetworks.avise
      se_version: "{{ avi_version }}"
      se_master_ctl_ip: 10.164.4.32
      se_master_ctl_username: admin
      se_master_ctl_password: "AviNetworks123!"
      se_cores: 4
