# Simple application name foo
# It has following characterstics
# Pool with two servers and HTTP health monitor
# Single VIP
# HTTP application
---
- hosts: localhost
  connection: local
  vars_files:
    - "vars/creds_unsecure.yml"
  vars:
    api_version: 17.1.2
    app_name: foo
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Create or Update Pool
      avi_pool:
        controller: "{{ avi_controller}}"
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        api_version: "{{ api_version }}"
        name: "{{app_name}}-pool"
        health_monitor_refs: '/api/healthmonitor?name=System-HTTP'
        cloud_ref: '/api/cloud?name=Default-Cloud'
        servers:
          - ip:
               addr: '10.90.64.16'
               type: 'V4'
          - ip:
               addr: '10.90.64.14'
               type: 'V4'

    - name: Create Virtual Service
      avi_virtualservice:
        controller: "{{ avi_controller}}"
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        api_version: "{{ api_version }}"
        name: "{{app_name}}"
        pool_ref: "/api/pool?name={{app_name}}-pool"
        cloud_ref: '/api/cloud?name=Default-Cloud'
        vip:
          - ip_address:

              addr: '10.90.64.222'
              type: 'V4'
            vip_id: '1'
        services:
          - port: 80

