---
- hosts: localhost
  vars:
    controller: "{{ controller }}"
    username: admin
    password: "{{ password }}"
  connection: local
  tasks:
    - name: test
      debug: msg="{{ controller }}"
    - name: Fetch Avi Version
      avi_api_version:
        controller: "{{ controller }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: avi_version
    - debug: msg="{{avi_version}}"
