# Create a certificate SSL Certificate
---
- hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avisdk
  tasks:
    - debug: msg="Private Key is {{ lookup('file', 'private_key.pem') }}"
    - debug: msg="Public Cert is {{ lookup('file', 'certificate.crt')}}"
    - avi_sslkeyandcertificate:
        controller: "{{controller}}"
        username: admin
        password: "{{password}}"
        tenant: admin
        api_version: 17.2.7
        key: "{{ lookup('file', 'private_key.pem') }}"
        certificate:
          self_signed: true
          certificate: "{{ lookup('file', 'certificate.crt')}}"
        type: SSL_CERTIFICATE_TYPE_VIRTUALSERVICE
        name: MyTestCert
