# ansible-playbook playbook.yml --extra-vars "rhn_username=myuser rhn_password=foo eth0=ens10001 eth1=ens10002"

# Notes:
#   Requirements:
#     pip install libselinux-python
#
---
- hosts: 10.164.4.15
  vars:
    interface_1: ens1f0
    interface_2: ens1f1
    rhn_username: "eric.sysmin"
    rhn_password: "1FastBee8192!"
  # environment:
  #   http_proxy: http://104.255.50.254:8080
  #   https_proxy: http://104.255.50.254:8080
  pre_tasks:
    # - name: Disable SELinux on this host
    #   selinux: state=disabled
    # - name: Restart machine
    #   shell: sleep 2 && shutdown -r now "Restarting with SELinux Disabled"
    #   async: 1
    #   poll: 0
    #   become: true
    #   ignore_errors: true
    # - name: Wait for the server to come back
    #   local_action: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} search_regex=OpenSSH state=started delay=10 timeout=300
    - name: Enable ipv4 forwarding
      sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
    - name: Disable and stop Firewalld
      service: name="firewalld" state="stopped" enabled="no"
    - name: Disable and stop NetworkManager
      service: name="NetworkManager" state="stopped" enabled="no"
    - name: Make sure yum-cron is removed
      yum: name=yum-cron state=absent
    - name: Docker | Storage Driver | devicemapper
      shell: df -h | grep docker-thinpool | awk '{print $1}'
      register: block_device_var
    - name: Unmount docker-thinpool
      mount: name=/docker-thinpool state=unmounted
    - name: Remove docker-thinpool mount
      mount: name=/docker-thinpool state=absent
    # http://docs.ansible.com/ansible/redhat_subscription_module.html
    - redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        autosubscribe: true
  roles:
    - role: avinetworks.docker
      storage_driver: devicemapper
      block_device: /dev/sda3
      #block_device: "{{ block_device_var.stdout }}"
    - role: avinetworks.network_interface
      network_bond_interfaces:
        - device: bond0
          onboot: yes
          bootproto: none
          nm_controlled: 'no'
          bond_slaves: ["{{ interface_1 }}", "{{ interface_2 }}"]
          bond_miimon: 100
          bond_mode: 4
          bond_xmit_hash_policy: layer3+4
          bond_use_carrier: 1
