# ansible-playbook playbook.yml --extra-vars "rhn_username=myuser rhn_password=foo interface_1=ens10001 interface_2=ens10002"
# for this playbook to work it requires Ansible 2.1.0
# Notes:
#   Requirements:
#     yum install -y libselinux-python
#
# Please make sure your hosts are in your Inventory (/etc/ansible/hosts) or are in a supplied hosts file to ansible using `-i`
---
- hosts: avicontroller
  vars:
    interface_1: "{{ interface_1 }}"
    interface_2: "{{ interface_2 }}"
    rhn_username: "{{ rhn_username }}"
    rhn_password: "{{ rhn_password }}"
    disable_selinux: false
# Enable these if you need to provide a proxy environment to the server for internet access
# environment:
#   http_proxy: "{{ http_proxy }}"
#   https_proxy: "{{ https_proxy }}"
  pre_tasks:
    - name: Disable SELinux on this host
      selinux: state=disabled
      when: disable_selinux
    - name: Restart machine
      shell: sleep 2 && shutdown -r now "Restarting with SELinux Disabled"
      async: 1
      poll: 0
      become: true
      ignore_errors: true
      when: disable_selinux
    - name: Wait for the server to come back
      local_action: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} search_regex=OpenSSH state=started delay=10 timeout=300
      when: disable_selinux
    - name: Enable ipv4 forwarding
      sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
    - name: Disable and stop Firewalld
      service: name="firewalld" state="stopped" enabled="no"
    - name: Disable and stop NetworkManager
      service: name="NetworkManager" state="stopped" enabled="no"
    - name: Make sure yum-cron is removed
      yum: name=yum-cron state=absent
    - name: Find the docker-thinpool device
      shell: df -h | grep docker-thinpool | awk '{print $1}'
      register: block_device_var
    - name: unmount docker-thinpool
      shell: umount /docker-thinpool
      failed_when: false
    - name: Remove docker-thinpool mount
      shell: sed -i '/.*docker-thinpool.*/d' /etc/fstab
      failed_when: false
    # http://docs.ansible.com/ansible/redhat_subscription_module.html
    - redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        autosubscribe: true
  roles:
    - role: avinetworks.docker
      storage_driver: devicemapper
      block_device: "{{ block_device_var.stdout }}"
    - role: avinetworks.network_interface
      network_bond_interfaces:
        - device: bond0
          onboot: yes
          bootproto: none
          nm_controlled: 'no'
          bond_slaves: ["{{ interface_1 }}", "{{ interface_2 }}"]
          bond_miimon: 100
          bond_mode: 4
          bond_xmit_hash_policy: layer3+4
          bond_use_carrier: 1
