---
# tasks file for avinetworks.avicontroller
- name: Avi Controller | Check minimum requirements
  include: requirements.yml
  tags:
    - requirements

- name: Avi Controller | Check for existing avicontroller service
  stat:
    path: "{{ item }}"
  register: service_installed
  with_items:
    - /etc/systemd/system/avicontroller.service
    - /etc/init.d/avicontroller

- name: Avi Controller | Stop avicontroller service
  service:
    name: avicontroller
    enabled: no
    state: stopped
  when: "{{ item.stat.exists == true }}"
  with_items: "{{ service_installed.results }}"

- name: Avi Controller | Perform Docker tasks
  include: docker.yml

- name: Avi Controller | Install the Avi Controller systemd service
  include: services/systemd.yml
  when: ansible_service_mgr == 'systemd'

- name: Avi Controller | Install the Avi Controller init.d service
  include: services/initd.yml
  when: ansible_service_mgr != 'systemd'

- name: Avi Controller | Copy setup.json to controller
  copy:
    src: "{{ setup_json }}"
    dest: "{{ con_disk_path }}/setup.json"
  when: setup_json != None

- name: Avi Controller | Start Avi Controller service
  service:
    name: avicontroller
    enabled: yes
    state: started
