avi_config:
  pool:
    - name: app1-pool
      #state: absent
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'

  virtualservice:
    - name: app1
      services:
        - port: 80
      pool_ref: '/api/pool?name=app1-pool'
      #pool_ref:
      #  state: absent
      vip:
        - ip_address:
            addr: "{{ app1_vip }}"
            type: 'V4'
          vip_id: '1'

  healthmonitor:
    - name: multiline_hm
      failed_checks: 1
      https_monitor:
        http_request: |-
          GET /index.html HTTP/1.0
          Connection: Close
        http_response_code:
        - HTTP_2XX
        - HTTP_3XX
      type: HEALTH_MONITOR_HTTP
